deployment:
  tasks:
    - export DEPLOYPATH=/home/kibriskonutproje/public_html/panel
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - $DEPLOYPATH composer install
